Feat/#2
nami-koko/thisABLE_front_2 pull request #3
Opened 2022-07-29 11:48 UTC by nami-koko

- add responsive Header for mobile and desktop
- add routing for logo and menus

<img height="500" alt="스크린샷 2022-07-29 오후 8 43 47" src="https://user-images.githubusercontent.com/86053064/181752113-ea88ec2d-4188-4d30-97ec-c6993daf7017.png">
<img width="500" alt="스크린샷 2022-07-29 오후 8 45 05" src="https://user-images.githubusercontent.com/86053064/181752121-4ae03ad5-f7f7-48eb-be07-21d6f9035ec5.png">

2022-07-29 18:21 UTC, seohyun319 requested changes
논의점 
- BaseLayout.tsx는 styled component 각 줄바꿈이 없는데 Header.tsx는 있어서 기본적으로 어떻게 맞출지
- export 선언 위치

2022-07-29 18:21 UTC, seohyun319 commented on components/common/Header.tsx
> +					handleMenuClick('/')
```
const handleMenuClick = (page: string) => {
  router.push(`/${page}`)
}
```
때문에 라우터에 '//'로 들어갈 것 같은데 정상 작동하나요? 
`router.push(page)`로 하고 기본적으로 / 포함된 경로 넣는 게 나을 것 같아요

2022-07-29 18:21 UTC, seohyun319 commented on components/common/Header.tsx
> +const Header = () => {
이 파일만 탭으로 된 것 같은데 나머지 파일처럼 space 2개로 맞춰주세욤

2022-07-29 23:22 UTC, nami-koko commented on components/common/Header.tsx
> +					handleMenuClick('/')
정상 작동 하긴 하는데 좋은 의견이네요 수정했어요~~ 감사합니다

2022-07-29 23:24 UTC, nami-koko commented on components/common/Header.tsx
> +const Header = () => {
formatter 설정 테스트 해보다가 되돌리는거 깜빡하고 올렸네요^^;  맞추고 useTabs 도 false로 설정했어요

2022-07-29 23:40 UTC, merged

2022-07-29 23:42 UTC, nami-koko commented
> 논의점
> 
> * BaseLayout.tsx는 styled component 각 줄바꿈이 없는데 Header.tsx는 있어서 기본적으로 어떻게 맞출지
> * export 선언 위치

 - styled 줄바꿈 없이
 - export 선언 위치는 export default const ~~ = () ... 이거랑 파일 끝에 export 하는걸 말하는거야??

2022-07-30 08:14 UTC, seohyun319 commented
> * export 선언 위치는 export default const ~~ = () ... 이거랑 파일 끝에 export 하는걸 말하는거야??

파일 끝에 export하는 것보다 export const ~~ 이렇게 하는 게 나을 것 같아서! @nami-koko